name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select latest stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Build
        run: xcodebuild -project "Token/Token.xcodeproj" -scheme Token -destination 'platform=macOS' MACOSX_DEPLOYMENT_TARGET=15.0 build

      - name: Test
        run: xcodebuild -project "Token/Token.xcodeproj" -scheme Token -destination 'platform=macOS' MACOSX_DEPLOYMENT_TARGET=15.0 test
